name: Bug report
description: Create a Bromite bug report
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Thanks for taking the time to submit a bug report.
        
        If you're looking for a place to ask a question, please use the [GitHub Discussions](https://github.com/bromite/bromite/discussions).
        
        Now, make sure you have acknowledged and completed this template before submitting your issue.
        
        Please read it carefully; we reserve the right to close and ignore your issue if you do not pay attention.
        
        Please note for the fourth checkbox that if the bug is reproducible on the Chromium build, then it might be a configuration issue or an upstream bug.
        Upstream bugs can be reported on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list).
        Do not forget to read the [Chromium project bug reporting guidelines](https://www.chromium.org/for-testers/bug-reporting-guidelines/).

  - type: checkboxes
    id: preliminary_checklist
    attributes:
      label: Preliminary checklist
      options:
        - label: "I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)."
          required: true
        - label: "I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue."
          required: true
        - label: "I have updated Bromite to the latest version. The bug is reproducible on this latest version."
          required: true
        - label: "I have made sure that this is not a [Chromium](https://github.com/bromite/chromium/releases) bug (in other words, this bug is related to functionality that does not exist in Chromium). I have done this by installing and testing the corresponding version of Chromium."
          required: true

  - type: input
    id: bromite_version
    attributes:
      label: Bromite version
      description: What version of Bromite are you running? Please specify a single version. Again, make sure you are running the latest version.
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android version
      description: What version of Android are you running? Please specify a single version.
      placeholder: (e.g. 8.1, 9, 10, etc.)
    validations:
      required: true

  - type: dropdown
    id: device_architecture
    attributes:
      label: What is your device's architecture?
      multiple: true
      options:
        - arm
        - arm64
        - x86
        - x64
    validations:
      required: true

  - type: input
    id: device_model
    attributes:
      label: Device model
      description: What is your device model? This can usually be found in your device's settings in the "About" section.
      placeholder: (e.g. `OnePlus 8 (IN2010)`, or `SM-G960UZKABST`, etc.)
    validations:
      required: true

  - type: textarea
    id: changed_flags
    attributes:
      label: Changed flags
      description: |
        These are the flags changed under `chrome://flags`.
        Report all blue-highlighted flags here.
        Those are the flags with non-default configuration.
        
        If no flags are changed, please say so.
      placeholder: (e.g. show-overdraw-feedback, enable-parallel-downloading, etc.)
    validations:
      required: true

  - type: dropdown
    id: system_webview
    attributes:
      label: Is this issue related to the System WebView?
      description: Please note that no support for System WebView installation is provided.
      multiple: true
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: incognito
    attributes:
      label: Is this bug happening in an incognito tab?
      multiple: true
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: adblock
    attributes:
      label: Is this bug related to adblock?
      description: Is the bug caused by the adblocker? You can test this by allowing ads for the site.
      multiple: true
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: bug_crash
    attributes:
      label: Is this bug a crash?
      description: |
        1. No.
        2. Yes, I have attached the crash report dump that I downloaded from `chrome://crashes`.
        3. Yes, this is a copy-paste of the crash dump:
      placeholder: |
        Paste the logcat dump individuated with 'adb logcat | grep chromium'.
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: Write a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: bug_steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        Try to explain how to cause the bug as clearly as possible.
        
        Also, do not just write "any website"; please specify which URLs can be used to reproduce the issue.
      placeholder: |
        Steps to reproduce the bug (e.g.):
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        Otherwise, ignore this section.
    validations:
      required: false
