name: Feature request
description: Create a Bromite feature request
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Thanks for taking time to submit a feature request.
        
        If you're looking for a place to ask a question, please use the [GitHub Discussions](https://github.com/bromite/bromite/discussions).
        
        Now, make sure you have acknowledged and completed this template before submitting your issue.
        
        Please read it carefully; we reserve the right to close and ignore your issue if you do not pay attention.
        
        Things to note:
          - Do not submit feature requests for extensions support or for adding a search engine.
          - Features unrelated to privacy will not be considered.
          - Do not ask "I would like feature X which is available in browser Y."

  - type: checkboxes
    id: preliminary_checklist
    attributes:
      label: Preliminary checklist
      options:
        - label: "I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)."
          required: true
        - label: "I have searched the existing issues for my feature request. This is a new ticket, NOT a duplicate or related to another issue."
          required: true
        - label: "I have read the [FAQ](https://github.com/bromite/bromite/blob/master/FAQ.md)."
          required: true
        - label: "I have read the [Wiki](https://github.com/bromite/bromite/wiki)."
          required: true

  - type: textarea
    id: patch_available
    attributes:
      label: Is there a patch available for this feature somewhere?
      description: If so, please provide a link and related license information.
    validations:
      required: true

  - type: textarea
    id: solution_description
    attributes:
      label: Describe the solution / feature you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
